// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the extension/redis_fleet_tracker component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("redis_fleet_tracker")
	ScopeName = "github.com/honeycombio/opentelemetry-collector-sampling-extensions/extension/redisfleettracker"
)

const (
	ExtensionStability = component.StabilityLevelDevelopment
)
