// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/honeycombio/opentelemetry-collector-sampling-extensions/extension/redisfleettracker")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/honeycombio/opentelemetry-collector-sampling-extensions/extension/redisfleettracker")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                       metric.Meter
	mu                                          sync.Mutex
	registrations                               []metric.Registration
	ExtensionRedisFleetTrackerHeartbeatFailures metric.Int64Counter
	ExtensionRedisFleetTrackerMemberCount       metric.Int64Gauge
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ExtensionRedisFleetTrackerHeartbeatFailures, err = builder.meter.Int64Counter(
		"otelcol_extension_redis_fleet_tracker_heartbeat_failures",
		metric.WithDescription("Number of heartbeat or observe errors. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ExtensionRedisFleetTrackerMemberCount, err = builder.meter.Int64Gauge(
		"otelcol_extension_redis_fleet_tracker_member_count",
		metric.WithDescription("Current live member count observed for the fleet. [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
